# SPDX-FileCopyrightText: 2024 Alec Delaney, for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Build CI

on: ["push", "pull_request"]

permissions: read-all

jobs:
  build:
    name: Run build CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        py-version: [
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
        ]
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest
        ]
    steps:
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run pre-commit via make
        run: |
          make check
      - name: Prepare tests
        run : |
          make test-prep
      - name: Run tests
        run: |
          make test-run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean up after tests
        run: |
          make test-clean
      - name: Create coverage.py XML report
        run: |
          coverage xml -o coverage_${{ matrix.os }}_${{ matrix.py-version }}.xml
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: coverage_${{ matrix.os }}_${{ matrix.py-version }}.xml
          flags: "${{ matrix.os }}-py-${{ matrix.py-version }}"
      - name: Test packaging
        run: |
          python -m build
