# SPDX-FileCopyrightText: 2024 Alec Delaney, for Adafruit Industries
# SPDX-License-Identifier: MIT

name: Run pre-commit checks

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/test-check.yml'
      - 'Makefile'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.pre-commit-config.yaml'
      - 'circfirm/**'
      - '.reuse/**'
      - 'LICENSES/**'

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.X'
      - name: Checkout the repository
        uses: actions/checkout@v6
      - name: Install requirements
        run: |
          pip install ".[dev]"
      - name: Run pre-commit via make
        run: |
          make check
